### ISSUE TITLE
NiftyExceptionLogger.java probably shouldn't log at error severity for broken connections

### ISSUE THREAD

**Issue by l3fang** [facebook/nifty#136]
nifty-core/src/main/java/com/facebook/nifty/core/NiftyExceptionLogger.java contains the following line:

log.error(exceptionEvent.getCause(), "Exception triggered on channel connected to %s", remoteAddress);

It is probably not at the error severity to log a broken connection. It would show up as ERROR on log4j based logs. This class of severity is usually reserved for things that shouldn't happen in production, but broken connection happens all the time in normal operations.

**Comment by charlie-harvey** [comment]
I also get this error:
org.jboss.netty.handler.codec.frame.TooLongFrameException: Maximum frame size of 67108864 exceeded

I spin up a service that takes sockets and someone hits it with http. It spews ERROR logs like crazy.

1. org.jboss.netty.handler.codec.frame.TooLongFrameException: Maximum frame size of 67108864 exceeded
2. org.apache.thrift.protocol.TProtocolException: Bad version in readMessageBegin
3. org.apache.thrift.transport.TTransportException: Buffer doesn't have enough bytes to read

I would change logging to OFF for this class, but then I wouldn't get any errors! All errors roll up to this class. Starting to think it isn't the best approach.
