### ISSUE TITLE
Upgrade to Netty 4

### ISSUE THREAD

**Issue by infynyxx** [facebook/nifty#50]
Netty 4 is nearing completion so, it would be lovely to see that up for use.

**Comment by sangupta** [comment]
Any updates on finalizing the Netty 4 branch soon?

**Comment by dmk23** [comment]
Anyone working on 4.1 ?

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jagadeeshmohan** [comment]
Any updates?

**Comment by PaniniGelato** [comment]
any updates?

**Comment by jagadeeshmohan** [comment]
any updates on this?

**Comment by wxpjimmy** [comment]
any updates on this?
