### ISSUE TITLE
Channel Statistics

### ISSUE THREAD

**Issue by AnnJ** [facebook/nifty#85]
What is the best way to expose Channel Statistics for gauging metrics (to ultimately log to Graphite)? Ideally, this would be implemented without modifying or duplicating existing Nifty classes.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
