### ISSUE TITLE
Can't change name of boss/worker threads

### ISSUE THREAD

**Issue by eungju** [facebook/nifty#97]
Name of all boss threads is "nifty-server-boss-%d". Name of all worker threads is "nifty-server-worker-%d". I can't add identifier for the threads. How can I change the name of the threads? I need a way to set niftyName of NettyConfigBuilderBase.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
